export default function TermsPage() {
  return (
    <main className="min-h-screen px-4 py-12">
      <div className="max-w-2xl mx-auto">
        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-8">Last updated: April 2026</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-gray-300">
          <section>
            <h2 className="text-xl font-semibold text-white">Service description</h2>
            <p>
              PodCraft is an AI-powered podcast generation service. You provide a topic and preferences,
              and we generate personalized audio content using artificial intelligence.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Account requirements</h2>
            <p>
              Some features (subscriptions, notifications) require an account. You are responsible
              for maintaining the security of your account. You must provide accurate information
              when creating an account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Generated content</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Podcasts are generated by AI and may contain inaccuracies. They are not a substitute for professional journalism.</li>
              <li>You retain rights to podcasts generated for your personal use.</li>
              <li>Generated content should not be presented as human-created journalism or reporting without disclosure.</li>
              <li>We do not guarantee the accuracy, completeness, or timeliness of generated content.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Acceptable use</h2>
            <p>You agree not to use PodCraft to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Generate content that is illegal, harmful, or violates others' rights</li>
              <li>Misrepresent AI-generated content as human-created news reporting</li>
              <li>Overwhelm the service with excessive automated requests</li>
              <li>Attempt to reverse-engineer or extract the underlying AI models</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Service availability</h2>
            <p>
              PodCraft is provided "as is" without warranty. We may modify, suspend, or discontinue
              any part of the service at any time. Scheduled podcast generation depends on third-party
              APIs and may occasionally be delayed or unavailable.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, PodCraft shall not be liable for any indirect,
              incidental, or consequential damages arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Changes to terms</h2>
            <p>
              We may update these terms from time to time. Continued use of PodCraft after changes
              constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Contact</h2>
            <p>
              For questions about these terms, contact us at legal@podcraft.app.
            </p>
          </section>
        </div>

        <div className="mt-8">
          <a href="/" className="text-brand-400 hover:text-brand-300 text-sm">
            Back to PodCraft
          </a>
        </div>
      </div>
    </main>
  );
}
